# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'posture_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.zoom = 1.5
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(int(1000*self.zoom), int(723*self.zoom))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, int(500*self.zoom), int(621*self.zoom)))
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(3)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)

        # self.label_2 = QtWidgets.QLabel(self.centralwidget)
        # self.label_2.setGeometry(QtCore.QRect(510, 10, 391, 301))
        # self.label_2.setObjectName("label_2")
        # font = QtGui.QFont()
        # font.setPointSize(15)
        # font.setBold(True)
        # font.setItalic(True)
        # font.setUnderline(False)
        # font.setWeight(75)
        # font.setKerning(True)
        # self.label_2.setFont(font)
        # self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        # self.label_2.setLineWidth(3)
        # self.label_2.setTextFormat(QtCore.Qt.AutoText)
        # self.label_2.setAlignment(QtCore.Qt.AlignCenter)


        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(int(550*self.zoom), int(330*self.zoom), int(411*self.zoom), int(331*self.zoom)))
        self.widget.setObjectName("widget")

        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.widget_plt = QtWidgets.QWidget(self.centralwidget)
        self.widget_plt.setGeometry(QtCore.QRect(int(550*self.zoom), int(10*self.zoom), int(411*self.zoom), int(300*self.zoom)))
        self.widget_plt.setObjectName("widget_plt")
        self.gridLayout_plt = QtWidgets.QGridLayout(self.widget_plt)
        self.gridLayout_plt.setObjectName("gridLayout_plt")

        self.pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)

        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)

        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)

        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 1, 1, 1)

        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 0, 1, 1)

        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, int(926*self.zoom), int(22*self.zoom)))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "燃烧我的卡路里！！！"))
        # self.label_2.setText(_translate("MainWindow", "人体姿态点信息"))
        self.pushButton_1.setText(_translate("MainWindow", "打开摄像头"))
        self.pushButton_2.setText(_translate("MainWindow", "停止运动"))
        self.pushButton_3.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_4.setText(_translate("MainWindow", "开始运动"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton5"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton6"))
